- get-started/content/quick-start/decision-automation.md
- get-started/content/quick-start/deploy.md
- get-started/content/quick-start/gateway.md
- get-started/content/quick-start/install.md
- get-started/content/quick-start/service-task.md
- get-started/content/quick-start/user-task.md
This PR includes a number of small typo fixes / wording updates following a proofread of the Quick Start. 
cc @felix-mueller
> chore(get-started): Edits based on complete proofread of updated Quick Start

- get-started/content/quick-start/decision-automation.md
- get-started/content/quick-start/deploy.md
- get-started/content/quick-start/gateway.md
- get-started/content/quick-start/service-task.md
@felix-mueller Note that I did _not_ yet add a screenshot of the console at the end of the "Deploy the Process" section but did change the language a bit to make this more clear.
> chore(get-started): Typo fixes, updated wording for clarity, links to more info

- enterprise/content/download.md
> chore(optimize): new optimize distribution names and 2.3.0 release

- enterprise/content/download.md
> chore(optimize): supported elasticsearch versions

- security/content/notices.md
> OPT-2162: chore(notice): describe how Optimize protects agains CSRF attacks

- enterprise/content/announcement.md
https://app.camunda.com/jira/browse/CAM-10793
> CAM-10793: announce Java 13

- enterprise/content/announcement.md
https://app.camunda.com/jira/browse/CAM-10899
> CAM-10899: announce retiring environments

- enterprise/content/announcement.md
> chore(announcements): new minimum elasticsearch version 6.4.0

- get-started/content/apache-maven.md
- get-started/content/cmmn11/project-setup.md
- get-started/content/dmn11/project-setup.md
- get-started/content/java-process-app/project-setup.md
- get-started/content/javaee7/install.md
- get-started/content/javaee7/project-setup.md
- get-started/content/quick-start/decision-automation.md
- get-started/content/quick-start/gateway.md
- get-started/content/quick-start/install.md
- get-started/content/quick-start/service-task.md
- get-started/content/spring-boot/project-setup.md
- get-started/content/spring/project-setup.md
* update all getting started guides
related to CAM-11030
> [CAM-11030] 7.12 release

- config/live/.htaccess
- test/HttpRedirectionTest.yml
> [CAM-11031] chore(release): set values for 7.12

- enterprise/content/announcement.md
> chore(optimize): add new cambpm version support to announcements

- enterprise/content/announcement.md
> chore(announcements): Optimize Adopt OpenJDK support

- enterprise/content/announcement.md
> chore(announcements): Optimize Java 13 support

- enterprise/content/announcement.md
* announce ElasticSearch support
related to #OPT-3105
> chore(annoucements): add Optimize 3.0 announcements

- enterprise/content/announcement.md
> CAM-11609: annouce 7.13

- enterprise/content/announcement.md
> CAM-11671: announce end of support for WLS 12R1

- enterprise/content/announcement.md
> CAM-11456: doc(support): add wildfly 19 announcement

- enterprise/content/download.md
> chore(enterprise): move Run to top of the list

- get-started/content/apache-maven.md
> CAM-11511: add known issue of artifactory

- enterprise/content/announcement.md
> chore(announcements): Add Optimize 3.1.0 to announcements

- enterprise/content/announcement.md
- for JS external task client
related to CAM-11841
> CAM-11841: announce changes in supported Node versions

- get-started/content/javaee7/install.md
- get-started/content/javaee7/project-setup.md
> chore(get-started): update platform to 7.13.0 

- get-started/content/spring/project-setup.md
> CAM-11857: chore(release): adjust spring framework getting started guide

- enterprise/content/announcement.md
> chore(announcements): raise supported engine version for Optimize 3.1

- get-started/content/quick-start/deploy.md
> [CAM-12099] Correction

- get-started/content/dmn/model.md
> [CAM-12099] Correction in hyperlink

- get-started/content/dmn/model.md
We can remove this broken link and leave it as plain text as configuring auto-sync in eclipse is o way related to Camunda.
related to CAM-12099
> [CAM-12099] Link is broken

- security/content/notices.md
> chore(notice): add note on security headers added to Optimize

- enterprise/content/announcement.md
- also announces retirement of Wildfly 10 support
related to CAM-12141
> CAM-12141: announce 7.15

- enterprise/content/announcement.md
> chore(env): add support for MS SQL Server 2019

- enterprise/content/announcement.md
> chore(docs): add support for WildFly 20

- enterprise/layouts/index.html
> docs(enterprise): remove dead pricing link

- enterprise/content/announcement.md
> chore(env): add support for JBoss EAP 7.3

- enterprise/content/announcement.md
Related to CAM-12071, CAM-12201
> CAM-12071: doc(db): announce support for cockroachdb v20.1.3

- get-started/content/spring-boot/project-setup.md
> chore(get-started): adjust spring boot gsg for 7.14.0

- get-started/content/javaee7/install.md
- get-started/content/javaee7/project-setup.md
> chore(get-started): adjust javaee7 gsg for 7.14.0

- get-started/content/spring/project-setup.md
- get-started/content/spring/shared-process-engine.md
> CAM-12356: chore(release): adjust spring gsg for 7.14

- get-started/content/cmmn11/install.md
- get-started/content/cmmn11/project-setup.md
> CAM-12357: chore(get-started): bump cmmn example to 7.14.0

- get-started/content/dmn/install.md
- get-started/content/dmn/project-setup.md
> CAM-12358: chore(get-started): bump dmn to 7.14.0

- enterprise/content/announcement.md
> chore(optimize): cam bpm 7.14.0 support and dropped 7.11.x support

- get-started/content/rpa/_index.md
> fix(get-started): fix rpa download link

- enterprise/content/announcement.md
> chore(optimize): Optimize 3.3 new elasticsearch support announcements

- enterprise/content/announcement.md
> chore(elasticsearch): remove support for Elasticsearch 7.0, 7.1, and 7.2

- enterprise/content/announcement.md
> CAM-12846: announce Aurora Postgres 10.13 support

- enterprise/content/announcement.md
> chore(docs): add support for WildFly 21

- enterprise/content/announcement.md
> feat(enterprise): announce Postgres 10.13 support

- enterprise/content/announcement.md
> CAM-13079: announce end of support with 7.15

- enterprise/content/announcement.md
> CAM-10972: doc(db): add support for mysql 8

- get-started/content/rpa/_index.md
Closes https://jira.camunda.com/browse/CAM-13200
> chore(rpa): update cloud connect download link

- enterprise/content/announcement.md
> CAM-12944: doc(env): add wildfly 22 support

- enterprise/content/download.md
> chore(download): add RPA Bridge to downloads

- enterprise/content/announcement.md
> CAM-12946: doc(db): add postgresql 13 support

- enterprise/content/announcement.md
> chore(enterprise): add support for Aurora 4.0.0

- config/live/robots.txt
related to CAM-13186
Note: only merge after all branches were updated with new header template
> chore(index): only index newest version

- enterprise/content/announcement.md
> chore(optimize): remove support for Elasticsearch 7.3 and 7.4, add support for 7.11

- enterprise/content/announcement.md
> chore(optimize): remove support for Elasticsearch 7.5.0

- README.md
Added link directly to hugo v0.50 and clarification on where to run build command.
> Clarity on how and where to run hugo

- get-started/content/spring/project-setup.md
- get-started/content/spring/service-task.md
> chore(get-started): update spring guide

- enterprise/content/announcement.md
> chore(optimize): drop of 7.12.x support, added 7.15 support

- enterprise/content/download.md
> chore(release): adjust RPA Bridge download link

- get-started/content/java-process-app/project-setup.md
> 7.15 release java

- config/live/.htaccess
- config/stage/.htaccess
> chore(redirect): use current versions start page

- get-started/content/quick-start/install.md
> CAM-13390: mention that other JDKs can be used

- config/stage/.htaccess
> chore(redirect): redirect to current version optimize start page

- enterprise/content/announcement.md
> docs(java): remove Optimize support for Java 8

- enterprise/content/announcement.md
> chore(elasticsearch): increase minimum supported ES version to 7.8.0

- test/HttpRedirectionTest.yml
- with CAM-13499 we missed updating the tests
related to CAM-13522
> CAM-13522: update redirect test expectations

- security/content/notices.md
related to https://github.com/camunda/cawemo/issues/8299
> feat(security): publish notice 44

- enterprise/content/announcement.md
> chor(es): Add Elasticsearch 7.12 and 7.13 support

- get-started/content/quick-start/deploy.md
Clarify model/diagram deployment support across Camunda Cloud and Camunda Platform
Related to [CAM-13703](https://jira.camunda.com/browse/CAM-13703).
> CAM-13703: docs(quickstart): Add modeler deployment note

- enterprise/content/announcement.md
> chore(enterprise): add JBoss EAP 7.4 support

- security/content/notices.md
related to https://github.com/camunda/cawemo/issues/9028
> feat(security): publish notice 46

- get-started/content/dmn/project-setup.md
> chore(get-started): update dmn getting started guide

- get-started/content/javaee7/project-setup.md
> chore(get-started): update JavaEE getting started guide

- get-started/content/quick-start/service-task.md
> chore(get-started): adjust quickstart guide

- get-started/content/java-process-app/project-setup.md
> chore(get-started): update Java getting started guide

- get-started/content/spring-boot/project-setup.md
> CAM-13904: update Spring Boot guide to 7.16.0

- get-started/content/spring/project-setup.md
> chore(get-started): update Spring getting started guide

- get-started/content/rpa/installation.md
> chore(get-started): adjust rpa guide

- enterprise/content/announcement.md
> chor(es): Add support for Elasticseach 7.14 & 7.15

- enterprise/content/announcement.md
relates to #OPT-5680
3 months after previous releases end of support
> fix(announcement): end of maintenance for Optimize 3.5 & 3.6

- security/content/notices.md
related to https://github.com/camunda/cawemo/issues/9888
> feat(security): publish notice 49

- enterprise/content/announcement.md
> chore(optimize): Optimize 3.6.5/3.7.0 announcement

- enterprise/content/announcement.md
Part of https://github.com/camunda/cawemo/issues/8964
> chore(cawemo): announce Cawemo 1.10

- enterprise/content/announcement.md
> chor(es): Remove support for Elasticsearch 7.8.0/7.9.0

- enterprise/content/announcement.md
> chore(announcement): add support for MariaDB 10.6

- get-started/content/quick-start/service-task.md
See this forum post for further details: https://forum.camunda.org/t/can-not-get-quickstart-s-deployment-to-work/32829/5
> add Camunda Platform to File selection

- enterprise/content/announcement.md
> CAM-14346: announce changes in supported environments

- config/banners.html
> CAM-14370: fix careers page links in banner

- enterprise/content/download.md
> CAM-14371: clarify downloads for JBoss EAP

- enterprise/content/announcement.md
> chore(elastic): support for Elasticsearch 7.17.0

- enterprise/content/download.md
- security/content/notices.md
Related to https://github.com/camunda/cawemo/issues/10276
> 10276 cawemo 1.9.1

- enterprise/content/announcement.md
> feat(db2): add support for DB2 11.5

- enterprise/content/announcement.md
This reverts commit 9e1baee49c075472d53a7ff06fdff82ef588c3df.
cc @MoAtCamunda 
Closes camunda/cawemo#10412
> Revert "chore(cawemo): announce Cawemo 1.10"

- build.gradle
- get-started/content/apache-maven.md
> Change to the new artifactory domain

- get-started/content/rpa/installation.md
- get-started/content/rpa/orchestrating-bots.md
* RPA getting started guide:
* Remove versioned links for RPA Bridge and Run
* Fix link to element templates documentation
> adjust RPA GSG

- config/live/.htaccess
- config/stage/.htaccess
> chore(config): fix javadocs redirects

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/10436
**Do not merge before version 1.9.2 is released.**
> Cawemo 1.9.2

- get-started/content/javaee7/project-setup.md
> chore(release): migrate JavaEE get started guide to 7.17.0

- config/live/.htaccess
- test/HttpRedirectionTest.yml
> CAM-14259: chore(release): set 7.17 as default version

- config/live/.htaccess
- config/stage/.htaccess
- test/HttpRedirectionTest.yml
- not needed anymore due to doc home move for dev/latest
> fix(optimize): remove deprecated redirect rules

- get-started/content/apache-maven.md
Details in the ticket
Related to INFRA-3237
> chore(artifactory): mention AWS S3 usage more prominently

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/10536
> 10536 cawemo 1.9.3

- security/content/security-policy.md
Update the security policy with the latest PenTest result Q2-2022 for Camunda automation Platform and Optimize
> feat(security-policy): add 2022-q2 pentest result

- enterprise/content/release-policy.md
This adds the new release policy page to the C7 docs.
> docs(enterprise): update release policy

- enterprise/content/announcement.md
Related to CAM-14611, CAM-14669
> chore(enterprise): announce end of support JBossEAP 7.0 / 7.1

- enterprise/content/announcement.md
> chore(enterprise): add Aurora 11 to announcements

- get-started/content/java-process-app/install.md
> chore(get-started): adjust tomcat download link

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/10730.
> Cawemo 1.9.4

- get-started/content/apache-maven.md
related to the Nexus URL removal.
> chore(apache-maven): remove Nexus and links to it

- get-started/content/quick-start/service-task.md
> chore(get-started): adjust quick start guide

- get-started/content/javaee7/project-setup.md
> chore(javaee): update getting started guide

- get-started/content/spring/project-setup.md
> chore(get-started): adjust spring for 7.18.0

- get-started/content/java-process-app/project-setup.md
> chore(get-started): adjust Java process application

- config/live/.htaccess
- config/stage/.htaccess
related to camunda/camunda-bpm-platform/issues/2851
> chore(config): add form-js redirect

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/10794
> feat(security): publish notice 78

- enterprise/content/announcement.md
Part of https://github.com/camunda/cawemo/issues/10794
> chore(release): update Cawemo release announcements

- enterprise/content/announcement.md
Related to camunda/camunda-bpm-platform#2778
> chore(enterprise): add AP 7.19 announcement

- enterprise/content/announcement.md
related to camunda/camunda-bpm-platform#2881
> chore(enterprise): add xtac update details

- security/content/report-vulnerability.md
- security/content/security-policy.md
related to camunda/camunda-bpm-platform#2973
> 2973: update trust center links

- enterprise/content/download.md
> chore(docs): remove preview releases from Optimize download page

- enterprise/content/support.md
Related to https://github.com/camunda/camunda-bpm-platform/issues/3047
> Update doc support prioritization

- enterprise/content/announcement.md
- enterprise/content/download.md
- security/content/notices.md
> docs: update cawemo documentation for patch release 1.9.6

- enterprise/content/download.md
> chore(docs): add warning about ES support to download page

- config/live/.htaccess
- config/stage/.htaccess
related to https://github.com/camunda/camunda-bpm-platform/issues/2733
> chore(config): add redirects for archived GSGs

- get-started/content/quick-start/service-task.md
- get-started/content/quick-start/user-task.md
related to /camunda/camunda-bpm-platform/issues/2910
> chore(release): migrate quickstart guide to 7.19

- get-started/content/spring-boot/project-setup.md
related to camunda/camunda-bpm-platform#2913
> chore(get-started): prepare spring boot guide

- get-started/content/dmn/project-setup.md
related to camunda/camunda-bpm-platform/issues/2911
> chore(release): adjust dmn getting started guide for 7.19

- enterprise/themes/camunda/layouts/partials/footer.html
- get-started/themes/camunda/layouts/partials/footer.html
- security/themes/camunda/layouts/partials/footer.html
related to camunda/camunda-bpm-platform#3309
> chore(project): update privacy link

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11142
> Cawemo 1.9.7

- get-started/content/archive/javaee7/service-task.md
https://github.com/camunda/camunda-bpm-platform/issues/3447
> 3447 drop handling jpa entities as variables

- enterprise/content/download.md
related to camunda/camunda-bpm-platform#3509
> chore(enterprise): clarify max supported engine version for RPA bridge

- enterprise/content/download.md
related to camunda/camunda-bpm-platform#3582
> chore(downloads): remove standalone web apps

- enterprise/content/download.md
Remove CMMN reference from the enterprise download page
> remove CMMN reference

- enterprise/content/download.md
- get-started/content/rpa/installation.md
Related to https://github.com/camunda/camunda-bpm-platform/issues/3606
> chore(rpa): remove RPA support for 7.20

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/11313
> Cawemo 1.9.9

- enterprise/content/download.md
https://github.com/camunda/camunda-bpm-platform/issues/3479
> chore(download): add standalone webapp note

- enterprise/content/download.md
> chore(download): keep only latest alpha of optimize

- enterprise/content/announcement.md
Related to https://github.com/camunda/camunda-bpm-platform/issues/3587
> chore(enterprise): add wildfly 29 to 7.20 announcement

- enterprise/content/announcement.md
related to https://github.com/camunda/camunda-bpm-platform/issues/3419
> chore(enterprise): bump Quarkus support to 3.2

- enterprise/content/announcement.md
> chore(docs): add Optimize 3.11 to docs announcements page

- get-started/content/dmn/install.md
- get-started/content/dmn/project-setup.md
related to camunda/camunda-bpm-platform#3320
> chore(get-started-dmn): adjust to 7.20

- get-started/content/spring-boot/project-setup.md
https://github.com/camunda/camunda-bpm-platform/issues/3322
> chore(starter): update to 7.20

- get-started/content/apache-maven.md
Add note to Spring 6 maven module
> chore(get-started): add spring 6 module to apache maven page

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/11564
> Cawemo 1.9.12

- enterprise/content/announcement.md
Closes https://github.com/camunda/cawemo/issues/11601
NOTE: The SaaS announcement has been agreed with @crobbins215 ; the On-premises announcement has to be peer-reviewed completely. I'm not sure if what I put there is enough.
> chore(docs): add cawemo EOL announcement

- enterprise/content/announcement.md
See https://github.com/camunda/camunda-docs-static/pull/429#discussion_r1461847257
> chore(docs): fix links to migration options

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11618
> docs(cawemo): add changes related to 1.9.13

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11712
Depends on https://github.com/camunda/camunda-docs-cawemo/pull/236
> docs(cawemo): add notice 105 and changes to the download page

- get-started/content/apache-maven.md
- get-started/content/dmn/project-setup.md
https://github.com/camunda/camunda-bpm-platform/issues/3834
> chore(get-started): bump dmn gsg to 7.21

- get-started/content/spring-boot/project-setup.md
https://github.com/camunda/camunda-bpm-platform/issues/3836
> chore(get-started): bump spring boot gsg to 7.21

- get-started/content/apache-maven.md
- get-started/content/dmn/project-setup.md
- get-started/content/quick-start/install.md
- get-started/content/quick-start/service-task.md
- get-started/content/spring-boot/project-setup.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3833
> chore(quick-start): Bump External Task Client Version

- enterprise/content/announcement.md
- enterprise/content/download.md
> chore(release): update downloads page for april 2024 releases

- enterprise/content/download.md
- security/content/notices.md
Related to https://github.com/camunda/cawemo/issues/11725
> chore(documentation): update information for Cawemo 1.9.16 patch release

- enterprise/content/download.md
- get-started/content/archive/rpa/installation.md
Relates to https://github.com/camunda/cawemo/issues/11813
> chore(cawemo): remove references to SaaS

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11774
> docs(cawemo): add notice 109 and changes to the download page

- enterprise/content/announcement.md
Closes https://github.com/camunda/cawemo/issues/11820
> chore(cawemo): document support offering

- enterprise/content/announcement.md
Fixes indentation issue introduced in https://github.com/camunda/camunda-docs-static/pull/468
> Cawemo 11820 maintenance support

- enterprise/content/support.md
Ticket priority names in JIRA will be updated tomorrow. See https://github.com/camunda/support/issues/89 for context.
> New Support ticket priority names

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11892
> docs(cawemo): Cawemo 1.9.19 release

- get-started/content/quick-start/service-task.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4520
> chore(quick-start): Adjust JAXB Dependency

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11931
> docs(cawemo): Cawemo 1.9.20 release

- get-started/content/apache-maven.md
- get-started/content/dmn/project-setup.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4253
> chore(get-started): Bump Version to 7.22.0

- get-started/content/spring-boot/project-setup.md
Related to https://github.com/camunda/camunda-bpm-platform/issues/4254
> chore(get-started): bump spring-boot get started guide to 7.22

- enterprise/content/announcement.md
related to camunda/camunda-bpm-platform#4130
> chore(announcement): remove Spring Boot 3.2 support

- test/HttpRedirectionTest.yml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4273
> chore(release): update smoke tests to version 7.22

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/11937
> docs(cawemo): Cawemo 1.9.21 release

- enterprise/content/download.md
- security/content/notices.md
Part of https://github.com/camunda/cawemo/issues/12018
> docs(cawemo): Cawemo 1.9.22 release

- config/banners.html
related to camunda/camunda-bpm-platform#4750
> chore(banners): adjust open positions banner

- enterprise/content/announcement.md
- enterprise/content/download.md
https://github.com/camunda/team-automation-platform/issues/216
> chore(download): add optimize alpha in download page

- enterprise/content/announcement.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4165
> chore(enterprise/content): Add Postgres 17

- enterprise/content/announcement.md
**Related-to**: https://github.com/camunda/camunda-bpm-platform/issues/4165
**What**: [Documentation # point2](https://github.com/camunda/camunda-bpm-platform/issues/4165#:~:text=Add%20under%20Announcements,for%20PostgreSQL%2017)
> chore(announcements): Add Postgres 17

- config/stage/.htaccess
related to camunda/camunda-bpm-platform#4802
> chore(config/stage): add redirect from enterprise support page

- enterprise/content/download.md
- security/content/notices.md
related https://github.com/camunda/cawemo/issues/12069
> docs(cawemo): Cawemo 1.9.24 release

- enterprise/content/download.md
related https://github.com/camunda/cawemo/issues/12069
> docs(cawemo): update date for Cawemo 1.9.24 release

- security/content/notices.md
related https://github.com/camunda/cawemo/issues/12069
> docs(cawemo): update netty-common for Cawemo 1.9.24 release

- enterprise/content/download.md
related to camunda/team-automation-platform/issues/243
> chore(download): add optimize 3.15.0-alpha2 to download page

- enterprise/content/download.md
- security/content/notices.md
* Add Security Notices
* Update download
related to https://github.com/camunda/cawemo/issues/12112
> docs(cawemo): update to Cawmo 1.9.25

- enterprise/content/download.md
* add demo link
* add production link
* remove alpha mention
https://github.com/camunda/team-automation-platform/issues/253
> chore(enterprise): add Optimize 3.15.0 release

- enterprise/config.yaml
- enterprise/themes/camunda/layouts/_default/sitemap.xml
- enterprise/themes/camunda/layouts/partials/header.html
- get-started/config.yaml
- get-started/themes/camunda/layouts/_default/sitemap.xml
- get-started/themes/camunda/layouts/partials/header.html
- security/config.yaml
- security/themes/camunda/layouts/_default/sitemap.xml
- security/themes/camunda/layouts/partials/header.html
Related to https://github.com/camunda/team-automation-platform/issues/286
> chore(SEO): add canonical base path to repair sitemap and canonical links

- enterprise/content/download.md
- security/content/notices.md
- Add Security Notices
- Update download page
related to https://github.com/camunda/cawemo/issues/12155
⚠️ depends on https://github.com/camunda/camunda-docs-cawemo/pull/285
> docs(cawemo): update Cawemo to 1.9.26

- enterprise/content/download.md
related to 7.23.0-alpha3 release
> chore(release): add 7.23.0-alpha3 to downloads

- enterprise/content/announcement.md
PG 17 announcement should go to Camunda 7.23 with mention that will be in a patch of 7.22
> chore(enterprise): update 7.22/7.23 announcement

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/12177
> docs(cawemo): update Cawemo to 1.9.27

- get-started/content/dmn/deploy.md
- get-started/content/dmn/install.md
- get-started/content/dmn/project-setup.md
https://github.com/camunda/camunda-bpm-platform/issues/4688
> chore(get-started/DMN) update docs

- get-started/content/spring-boot/project-setup.md
https://github.com/camunda/camunda-bpm-platform/issues/4689
> chore(get-started): update SB guide to 7.23

- get-started/content/apache-maven.md
https://github.com/camunda/camunda-bpm-platform/issues/4714
> chore(get-started): update maven page

- get-started/content/quick-start/install.md
- get-started/content/quick-start/service-task.md
Related to https://github.com/camunda/camunda-bpm-platform/issues/4711
> chore(gsg): update jdk and version

- get-started/content/apache-maven.md
- get-started/content/dmn/deploy.md
- get-started/content/dmn/install.md
- get-started/content/dmn/project-setup.md
- get-started/content/quick-start/install.md
- get-started/content/quick-start/service-task.md
- get-started/content/spring-boot/project-setup.md
Squashed all commits in 7.23-release as part of [camunda/camunda-bpm-platform/issues/4687](https://github.com/camunda/camunda-bpm-platform/issues/4711)
> chore(get-started-guide) 7.23 release

- config/live/.htaccess
https://github.com/camunda/camunda-bpm-platform/issues/4712
> fix(config): javadoc latest

- enterprise/content/download.md
related to [#4971](https://github.com/camunda/camunda-bpm-platform/issues/4971)
> chore(deps): update es support

- enterprise/content/download.md
- security/content/notices.md
Related to https://github.com/camunda/cawemo/issues/12280
> chore(docs): update Cawemo 1.9.30

- enterprise/content/download.md
- security/content/notices.md
related https://github.com/camunda/cawemo/issues/12393
> docs(cawemo): add 1.9.33 release information

- get-started/content/spring-boot/project-setup.md
Related to https://github.com/camunda/camunda-bpm-platform/issues/5081
> chore(get-started): Update platform and spring boot versions in Spring Boot GSG

- get-started/content/dmn/project-setup.md
https://github.com/camunda/camunda-bpm-platform/issues/5079
> chore(get-started): update Camunda version to 7.24.0
