- get-started/content/quick-start/service-task.md
- get-started/content/quick-start/user-task.md
I was just going through the quick start guide and noticed that some wording can be improved to better understand what needs to be applied by the user.
Also, the behaviour of the checkbox seems to have changed. The previous version assumed, the `Executable` checkbox needs checking, however, it seems now to be checked by default.
> Minor changes to enhance understanding.

- enterprise/content/announcement.md
- get-started/content/cmmn11/install.md
- get-started/content/dmn11/install.md
- get-started/content/java-process-app/install.md
- get-started/content/javaee7/install.md
- also removes IE mentions from getting started guides
related to CAM-11938
> CAM-11938: announce end of support for IE 11

- get-started/content/dmn/model.md
- get-started/content/java-process-app/forms.md
- get-started/content/javaee7/start-form.md
- get-started/content/javaee7/task-form.md
- security/content/security-policy.md
Resolved typos in the documentation and removed inappropriate markdowns of application in guides
> docs(get-started+security): Fix mistakes in the documentation

- get-started/content/javaee7/install.md
- get-started/content/javaee7/project-setup.md
* removes the WildFly version as this does always create work and
does not provide much additional help for the guide
related to CAM-13216
> chore(get-started): bump versions in JEE guide

- config/live/.htaccess
relates to #OPT-5149
Tested on stage by previously merging #164.
Sample case, go to http://stage.docs.camunda.org/optimize/1.5/user-guide/frequency/
and switch to Version 3.3.
> chore(redirect): redirect to current version optimize start page

- config/stage/.htaccess
Implements the fix done in https://github.com/camunda/camunda-docs-static/pull/165 for Cawemo - for testing purposes only on stage, a follow-up PR for prod will be opened once it works.
(see https://github.com/camunda/cawemo/issues/8000)
> chore(redirect): redirect to current Cawemo version start page

- config/live/.htaccess
- config/stage/.htaccess
Implements the fix done in #167, #165 and #164 for Cawemo.
For a simple test case go to http://stage.docs.camunda.org/cawemo/1.6/foo
(see https://github.com/camunda/cawemo/issues/8000)
> chore(redirect): redirect to current Cawemo version start page if site not found

- config/live/.htaccess
relates to #OPT-5149
Thanks to @wollefitz for noticing this edge-case!
Testable on stage with  https://github.com/camunda/camunda-docs-static/commit/4f52e8e0bf4ce0d4bce5fc97f87fda9c0fcd2500
> chore(redirect): include latest version in invalid path handling rule

- config/live/.htaccess
- config/stage/.htaccess
- with the removal of the cmmn11 getting started guide, the redirects
produced an infinite loop
related to CAM-13499
> CAM-13499: avoid infinite redirect for cmmn11 urls

- get-started/content/quick-start/decision-automation.md
- get-started/content/quick-start/deploy.md
- get-started/content/quick-start/gateway.md
- get-started/content/quick-start/user-task.md
* The links to the Camunda web apps in the Quick Start guide need to have a backslash (/) at the end to work correctly.
Related to CAM-13585
> CAM-13585: fix(guide): adjust quick start web apps links

- security/content/report-vulnerability.md
- security/content/security-policy.md
* Removed Report a Vulnerability steps. Linked to [camunda.com/security](https://camunda.com/security#report-a-vulnerability). 
* Removed Security Policy content, except Penetration Testing section and table. Linked to camunda.com/security and camunda.com/security#security-issues-management.
Related to [CAM-13620](https://jira.camunda.com/browse/CAM-13620).
> CAM-13620: docs(security): remove duplicate content with camunda.com/security

- get-started/content/apache-maven.md
due to URL redirects, the existing links are still valid and alternatives are provided
related to [INFRA-2706](https://jira.camunda.com/browse/INFRA-2706)
As the existing information is quite slim on Nexus, I added all relevant information for Artifactory to have a possible workaround URL but did not go deeper details on why/how/... due it it being customer facing.
The change can be tested by using the currently deployed proxy:
https://app.camunda.com/nexus2/
e.g.
https://app.camunda.com/nexus2/service/rest/repository/browse/camunda-bpm/
https://app.camunda.com/nexus/service/rest/repository/browse/camunda-bpm/
https://camunda.jfrog.io/ui/native/camunda-bpm/
To check the repository settings one could as an example run a basic maven app and use it in the pom / settings.xml …
> chore(get-started): deprecate Nexus and add new artifact storage

- enterprise/content/download.md
- JBoss EAP 6 is no longer supported on 7.16
related to CAM-14208
> CAM-14208: remove JBoss AS 7 from 7.16 download pages

- enterprise/content/announcement.md
- we will not claim general h2 2.x support (see ticket for reasoning)
related to CAM-14205
> CAM-14205: clarify supported h2 minor version

- enterprise/content/announcement.md
https://github.com/camunda/camunda-bpm-platform/issues/3243
- As we retire EAP 7.2. and 7.3 we can also retire Wildfly 15 and 18
- Amazon Postgres 12 used for Amazon Aurora Postgres 12,  is maintained until 11/2024. It is removed as 7.20 has to be maintained until April 2025.
> Release Announcements 7.20

- config/live/.htaccess
- config/stage/.htaccess
The current config redirects you from https://docs.camunda.org/get-started/spring-boot/ to https://docs.camunda.org/get-started/archive/spring/ which is unwanted behaviour
Follow up of #344
> fix(config): set exact match for the archived get-started guides

- enterprise/content/download.md
Add the 3.11.0 alpha1 release to the downloads page.
> chore(download): add opt 3.11.0-alpha1 to download page

- enterprise/content/download.md
- security/content/notices.md
Relates to https://github.com/camunda/cawemo/issues/11417
> Add security notice 95 and change cawemo version on download page

- enterprise/content/announcement.md
Relates to https://github.com/camunda/camunda-docs/pull/4013 - the Cawemo migration guide will be removed from the C8 docs.
> chore(cawemo): remove link to migration guide

- get-started/content/quick-start/service-task.md
**Context**: Using the [example](https://docs.camunda.org/get-started/quick-start/service-task/#add-camunda-external-task-client-dependency) of documentation and starting the client results in a `ClassNotFoundException: jakarta.xml.bind.JAXBException`
The fix adjusts the jaxb dependency to use the same **jakarta** dependency as used in `camunda-bpm-platform`.
**Related-to**: https://github.com/camunda/camunda-bpm-platform/issues/4520
> chore(quick-start): Adjust JAXB Dependency

- enterprise/content/download.md
Adds the September 2024 Optimize releases to the downloads page.
> chore(download): add optimize september 2024 releases to download page

- enterprise/content/download.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4592
> chore(download): add 7.22.0-alpha5 to download page
